idle_bg = "#272822"
idle_fg = "#f8f8f2"
info_bg = "#66d9ef"
info_fg = "#272822"
good_bg = "#a6e22e"
good_fg = "#272822"
warning_bg = "#f4bf75"
warning_fg = "#272822"
critical_bg = "#f92672"
critical_fg = "#272822"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
