position: "top"
height: 44
start:
  - type: custom
    class: power-menu
    bar:
    - on_click: popup:toggle
      label: ⏻
      name: power-btn
      type: button
    popup:
    - orientation: vertical
      type: box
      widgets:
      - type: box
        widgets:
        - class: power-btn
          on_click: '!systemctl poweroff'
          label: ⏻
          type: button
        - class: power-btn
          on_click: '!systemctl reboot'
          label: 
          type: button
      - label: '{{60000:uptime -p | cut -d '' '' -f2-}}'
        name: uptime
        type: label
  - type: clock
    format: '%m/%d %H:%M'
  - type: workspaces
    name_map:
      '10': 󰍩,
    all_monitors: true
center:
end:
  - type: volume
  - type: music
    player_type: mpd
    format: '{title}    {artist}'
    truncate: end
    show_status_icon: false
    cover_image_size: 160
    host: '/home/malicean/.local/state/mpd/socket'
    music_dir: '/home/malicean/music/source'
  - type: upower
    icon_size: 16
  - type: script
    class: weather
    cmd: /home/malicean/.config/ironbar/scripts/weather.nu
    interval: 900000
