theme = "monokai"
icons = "material-nf"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "weather"
format = "{temp:2} / {humidity:3}% / {wind:3}"
interval = 60
service = { name = "openweathermap", units = "metric" }
autolocate = true

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_temperature = false
if_command = '[ -n "$(lsmod | rg nvidia)" ]'

[[block]]
block = "temperature"
collapsed = false
format = "{average:3}"
good = 40
idle = 60
warning = 80

[[block]]
block = "custom"
command = ''' [ "$(pactl get-source-mute @DEFAULT_SOURCE@ | rg '^Mute: (yes|no)$' -or '$1')" == "no" ] && echo -e "\uf130" Unmuted || echo -e "\uf131" Muted '''
on_click = ''' pactl set-source-mute @DEFAULT_SOURCE@ toggle '''
interval = 5
shell = "/bin/sh"

[[block]]
block = "custom"
command = ''' echo -ne "\uf9c4 " && asusctl profile -p | rg '^Active profile is (\w+)$' -or '$1' '''
on_click = ''' asusctl profile -n '''
interval = 5
shell = "/bin/sh"

[[block]]
block = "backlight"
format = "{brightness:3}"

[[block]]
block = "sound"
format = "{volume:3}"
show_volume_when_muted = true

[[block]]
block = "battery"
format = "{time:3} {power}"

[[block]]
block = "time"
interval = 5
format = "%a %d-%m %R"
