format = """
  $username\
  $hostname\
  $localip\
  $shlvl\
  $singularity\
  $kubernetes\
  $directory\
  $vcsh\
  $git_branch\
  $git_commit\
  $git_state\
  $git_metrics\
  $git_status\
  $hg_branch\
  $docker_context\
  $package\
  $buf\
  $c\
  $cmake\
  $cobol\
  $dart\
  $deno\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $golang\
  $haskell\
  $helm\
  $java\
  $julia\
  $kotlin\
  $lua\
  $nim\
  $nodejs\
  $ocaml\
  $perl\
  $php\
  $pulumi\
  $purescript\
  $python\
  $rlang\
  $red\
  $ruby\
  $rust\
  $scala\
  $swift\
  $terraform\
  $vlang\
  $vagrant\
  $zig\
  $nix_shell\
  $conda\
  $spack\
  $memory_usage\
  $aws\
  $gcloud\
  $openstack\
  $azure\
  $env_var\
  $crystal\
  $custom\
  $sudo\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $time\
  $status\
  $shell\
  $character"""

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[spack]
symbol = "🅢 "

[rust]
symbol = " "
