id = 677226551607033903
hosts = ["localhost:6600"]

[format]
details = "$title"
state = "on $album by $artist"
timestamp = "elapsed"
large_image = "notes"
small_image = ""
large_text = "$album"
small_text = ""
